[project]
name = "agenttooleval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "abhisek", email = "abhisek169@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "kaggle>=2.2.4",
    "kaggle-benchmarks>=0.6.1",
    "matplotlib>=3.11.2",
    "ollama>=0.6.3",
    "python-dotenv>=1.2.4",
]

[project.scripts]
agenttooleval = "agenttooleval:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
